<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

class ProductController extends Controller
{
    public function index(Request $request): View
    {
        $filter = $request->query('filter', 'active'); // Default to 'active'
        
        $query = Product::with('category');
        
        // Apply filter based on status
        if ($filter === 'active') {
            $query->where('is_active', true);
        } elseif ($filter === 'inactive') {
            $query->where('is_active', false);
        }
        // If filter is 'all', no additional where clause needed
        
        // Order by latest created first (descending)
        $products = $query->orderBy('created_at', 'desc')->paginate(15);

        return view('products.index', [
            'products' => $products,
            'filter' => $filter
        ]);
    }

    public function create(): View
    {
        return view('products.create');
    }

    public function store(Request $request): RedirectResponse
    {
        // Check if this is a multi-product submission
        if ($request->has('products') && is_array($request->products)) {
            return $this->storeMultipleProducts($request);
        }

        // Check if this is Individual IMEI mode
        if ($request->has('imei_entries') && is_array($request->imei_entries)) {
            return $this->storeIndividualImeiProducts($request);
        }

        // Original single product logic with bulk IMEI support
        $request->validate([
            'name' => 'required|string|max:255',
            'category_id' => 'required|string|max:255',
            'selling_price' => 'required|numeric|min:0',
            'cost_price' => 'nullable|numeric|min:0',
            'reorder_level' => 'required|integer|min:0',
            'description' => 'nullable|string', 
            'barcode' => 'nullable|unique:products,barcode|string|max:100',
            'origin' => 'nullable|string|max:100',
            'imei' => 'nullable|required_without:imei_list|unique:products|string|max:100',
            'imei_list' => 'nullable|required_without:imei|string',
        ]);

        $bulkImeis = [];
        if ($request->filled('imei_list')) {
            $bulkImeis = array_values(array_filter(array_map('trim', explode("\n", $request->imei_list))));
        }

        $category = Category::firstOrCreate(
            ['name' => $request->category_id],
            ['name' => $request->category_id]
        );
        
        $baseData = $request->only([
            'name', 'description', 'cost_price', 'selling_price', 'reorder_level', 'origin'
        ]);
        $baseData['category_id'] = $category->id;
        $baseData['quantity_in_stock'] = 1;
        $baseData['cost_price'] = $request->input('cost_price', 0);
        $baseData['total_cost'] = $baseData['cost_price'] * 1;
        $baseData['is_active'] = true;

        $createdCount = 0;

        if (!empty($bulkImeis)) {
            // BULK MODE - Multiple phones with different IMEIs
            foreach ($bulkImeis as $index => $imei) {
                if (Product::where('imei', $imei)->exists()) {
                    return back()->withErrors(['imei_list' => "IMEI $imei already exists."])->withInput();
                }

                $productData = $baseData;
                // SKU will be auto-generated by the model
                $productData['imei'] = $imei;
                $productData['barcode'] = ($index > 0) ? null : $request->barcode;

                Product::create($productData);
                $createdCount++;
            }
        } else {
            // SINGLE MODE
            $validated = $request->validate([
                 'quantity_in_stock' => 'nullable|integer|min:0',
            ]);
            
            $quantity = $request->input('quantity_in_stock', 0);
            
            $productData = $baseData;
            // SKU will be auto-generated by the model
            $productData['imei'] = $request->imei;
            $productData['barcode'] = $request->barcode;
            $productData['quantity_in_stock'] = $quantity;
            $productData['total_cost'] = $baseData['cost_price'] * $quantity;

            Product::create($productData);
            $createdCount = 1;
        }

        return redirect()->route('products.index')
            ->with('success', "$createdCount Product(s) created successfully");
    }

    private function storeIndividualImeiProducts(Request $request): RedirectResponse
    {
        // Validate the base product info and IMEI entries
        $request->validate([
            'name' => 'required|string|max:255',
            'category_id' => 'required|string|max:255',
            'description' => 'nullable|string',
            'origin' => 'nullable|string|max:100',
            'reorder_level' => 'required|integer|min:0',
            'imei_entries' => 'required|array|min:1',
            'imei_entries.*.imei' => 'required|string|max:100',
            'imei_entries.*.cost_price' => 'nullable|numeric|min:0',
            'imei_entries.*.selling_price' => 'required|numeric|min:0',
            'imei_entries.*.quantity' => 'required|integer|min:1',
        ]);

        // Check for duplicate IMEIs in the database
        foreach ($request->imei_entries as $entry) {
            if (!empty($entry['imei']) && Product::where('imei', $entry['imei'])->exists()) {
                return back()->withErrors(['imei_entries' => "IMEI {$entry['imei']} already exists in database."])->withInput();
            }
        }

        // Find or create category
        $category = Category::firstOrCreate(
            ['name' => $request->category_id],
            ['name' => $request->category_id]
        );

        $createdCount = 0;

        foreach ($request->imei_entries as $index => $entry) {
            // SKU will be auto-generated by the model
            $costPrice = $entry['cost_price'] ?? 0;
            $sellingPrice = $entry['selling_price'];
            $quantity = $entry['quantity'];

            $productData = [
                'name' => $request->name,
                'description' => $request->description,
                'imei' => $entry['imei'],
                'barcode' => ($index === 0) ? $request->barcode : null,
                'origin' => $request->origin,
                'category_id' => $category->id,
                'cost_price' => $costPrice,
                'selling_price' => $sellingPrice,
                'quantity_in_stock' => $quantity,
                'total_cost' => $costPrice * $quantity,
                'reorder_level' => $request->reorder_level,
                'is_active' => true,
            ];

            Product::create($productData);
            $createdCount++;
        }

        return redirect()->route('products.index')
            ->with('success', "$createdCount Product(s) created successfully with individual pricing");
    }

    private function storeMultipleProducts(Request $request): RedirectResponse
    {
        // Validate multiple products
        $request->validate([
            'products' => 'required|array|min:1',
            'products.*.name' => 'required|string|max:255',
            'products.*.category_id' => 'required|string|max:255',
            'products.*.sku' => 'required|string|max:100',
            'products.*.selling_price' => 'required|numeric|min:0',
            'products.*.cost_price' => 'nullable|numeric|min:0',
            'products.*.quantity_in_stock' => 'nullable|integer|min:0',
            'products.*.imei' => 'nullable|string|max:100',
            'products.*.reorder_level' => 'nullable|integer|min:0',
            'products.*.description' => 'nullable|string',
        ]);

        $createdCount = 0;
        $isAdmin = auth()->user()->isAdmin();

        foreach ($request->products as $index => $productData) {
            // Validate unique SKU
            if (Product::where('sku', $productData['sku'])->exists()) {
                return back()->withErrors(["products.$index.sku" => "SKU '{$productData['sku']}' already exists."])->withInput();
            }

            // Validate unique IMEI if provided
            if (!empty($productData['imei']) && Product::where('imei', $productData['imei'])->exists()) {
                return back()->withErrors(["products.$index.imei" => "IMEI already exists."])->withInput();
            }

            // Find or create category
            $category = Category::firstOrCreate(
                ['name' => $productData['category_id']],
                ['name' => $productData['category_id']]
            );

            // Prepare product data
            $product = [
                'name' => $productData['name'],
                'sku' => $productData['sku'],
                'imei' => $productData['imei'] ?? null,
                'barcode' => $productData['barcode'] ?? null,
                'description' => $productData['description'] ?? null,
                'category_id' => $category->id,
                'selling_price' => $productData['selling_price'],
                'cost_price' => $productData['cost_price'] ?? 0,
                'quantity_in_stock' => $productData['quantity_in_stock'] ?? 1,
                'reorder_level' => $productData['reorder_level'] ?? 10,
                'is_active' => true,
            ];

            // Calculate total cost
            $product['total_cost'] = $product['cost_price'] * $product['quantity_in_stock'];

            Product::create($product);
            $createdCount++;
        }

        return redirect()->route('products.index')
            ->with('success', "$createdCount Product(s) created successfully");
    }

    public function show(Product $product): View
    {
        return view('products.show', ['product' => $product]);
    }

    public function edit(Product $product): View
    {
        return view('products.edit', ['product' => $product]);
    }

    public function update(Request $request, Product $product): RedirectResponse
    {
        $isAdmin = auth()->user()->isAdmin();
        
        $rules = [
            'name' => 'required|string|max:255',
            'imei' => 'nullable|unique:products,imei,' . $product->id . '|string|max:100',
            'barcode' => 'nullable|unique:products,barcode,' . $product->id . '|string|max:100',
            'origin' => 'nullable|string|max:100',
            'description' => 'nullable|string',
            'category_id' => 'required|string|max:255', // Now accepts category name
            'quantity_in_stock' => 'nullable|integer|min:0',
            'reorder_level' => 'required|integer|min:0',
            'is_active' => 'boolean',
        ];

        if ($isAdmin) {
            $rules['cost_price'] = 'nullable|numeric|min:0';
            $rules['selling_price'] = 'required|numeric|min:0';
        }

        $validated = $request->validate($rules);

        // Find or create category by name
        $category = Category::firstOrCreate(
            ['name' => $validated['category_id']], // Search by name
            ['name' => $validated['category_id']]  // Create with this name if not found
        );

        // Replace category name with actual category ID
        $validated['category_id'] = $category->id;

        // Default cost_price to 0 if not provided
        if (!isset($validated['cost_price']) || is_null($validated['cost_price'])) {
            $validated['cost_price'] = 0;
        }

        // Auto-calculate total cost: cost_price × quantity_in_stock
        $quantity = $validated['quantity_in_stock'] ?? $product->quantity_in_stock;
        $validated['total_cost'] = $validated['cost_price'] * $quantity;

        $product->update($validated);

        return redirect()->route('products.show', $product)
            ->with('success', 'Product updated successfully');
    }

    public function destroy(Product $product): RedirectResponse
    {
        $product->update(['is_active' => false]);

        return redirect()->route('products.index')
            ->with('success', 'Product deactivated successfully');
    }

    public function addStock(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'product_id' => 'required|exists:products,id',
            'quantity' => 'required|integer|min:1',
            'reference' => 'nullable|string|max:255',
        ]);

        $product = Product::find($validated['product_id']);
        $previousStock = $product->quantity_in_stock;
        
        // Add stock
        $product->increment('quantity_in_stock', $validated['quantity']);
        
        // Optionally log the stock movement if you have a StockMovement model
        if (class_exists('App\Models\StockMovement')) {
            \App\Models\StockMovement::create([
                'product_id' => $product->id,
                'movement_type' => 'in',
                'quantity' => $validated['quantity'],
                'reference' => $validated['reference'] ?? 'Manual Stock Addition',
                'notes' => 'Added by ' . auth()->user()->name,
            ]);
        }

        return redirect()->route('products.show', $product)
            ->with('success', "Added {$validated['quantity']} units to {$product->name}");
    }
}